name: Deployando
on: [push, workflow_dispatch]
jobs:

  build:
    name: Actualizando
    runs-on: ubuntu-latest
    steps:
    - name: Actualizando la versión del tema de arde
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/themes/tema_omeka
          git pull
          chown -R www-data:www-data .
